# NumPy Cheat Sheet

In [191]:
import numpy as np

## Creating NumPy arrays using *List* and *Tuple*

In [192]:
# List to array
my_list = [-3, 0, 10, 20, 3]
list_to_array = np.array(my_list)

# tuple to array
my_tuple = (10, -3, 4.5, 15+4j)
tuple_to_array = np.array(my_tuple)

## *numpy.arange()*

In [193]:
# numpy.arange() method generates integer data type numbers in a range starting from [0, stop)
print np.arange(7)

# numpy.arange() method generates integer data type numbers in a range starting from [start, stop)
print np.arange(2,7)

# numpy.arange() method generates integer data type numbers in a range starting from [start, stop) with step size
print np.arange(1,10,2)

# numpy.arange(stop, step_size) -- doesn't work
print np.arange(10,2)

[0 1 2 3 4 5 6]
[2 3 4 5 6]
[1 3 5 7 9]
[]


In [194]:
# creating 3D array
my_3d_array = np.arange(80)

# (4, 2, 10) in the below line should be read as
# "there are four 2D arrays where each array has 2 rows and 10 columns" 
my_3d_array.shape = (4, 2, 10)
print my_3d_array

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]]


## *numpy.linspace()*

In [195]:
# Note that arange() function has [start, stop) whereas linspace has [start, stop]
# Note that arange() function generates int data type numbers whereas linspace() generates float data type numbers

# generate 5 numbers from [1,10]
my_linspace_array = np.linspace(1, 10, 5)
print my_linspace_array

# know the step size between numbers
my_linspace_array = np.linspace(1, 10, 5, retstep = True)
print my_linspace_array[0]
print my_linspace_array[1]

# generate numbers with different data type
my_linspace_array = np.linspace(1, 10, 5, dtype = 'int32')
print my_linspace_array

[  1.     3.25   5.5    7.75  10.  ]
[  1.     3.25   5.5    7.75  10.  ]
2.25
[ 1  3  5  7 10]


## *numpy.zeros()*

In [196]:
# numpy.zeros() function generates array with floating data type
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [197]:
# generate 2D array
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [198]:
# generate 3D array
np.zeros((5,3,6))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]])

In [199]:
# generate array with integer data type
np.zeros(10, dtype = 'int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

## *numpy.ones()*

In [200]:
# ones() function generates array of ones with default float data type
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [201]:
# generate 2D array of ones with integer datatype
np.ones((5,3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## Slice Arrays

In [202]:
my_array = np.arange(10, 20)
print my_array[0]
print my_array[3]

10
13


In [203]:
# creating and manipulating 2D arrays
my_array = np.arange(1,36)
my_array.shape = (7,5)
print my_array

# accessing specific elements
row = 2
column = 3
print my_array[row, column]
print my_array[row][column]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
14
14


In [204]:
# creating and manipulating 3D arrays
my_array = np.arange(1,81)
my_array.shape = (2,8,5)
print my_array

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]
  [61 62 63 64 65]
  [66 67 68 69 70]
  [71 72 73 74 75]
  [76 77 78 79 80]]]


In [205]:
my_array[0][2][2]

13

In [206]:
my_array[1][4][4]

65

In [207]:
# printing specific segments of array
my_array = np.arange(28).reshape(4, 7)
print my_array

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [208]:
print my_array[2:]

[[14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [209]:
print my_array[0:2]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [210]:
print my_array[:, :3]

[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [21 22 23]]


## Boolean Mask Arrays

### Using Python functions

In [211]:
# Print all numbers within [1,100] divisible by 5 
num_array = np.arange(1, 20)
print "numbers: ", num_array

div_by_5 = (num_array % 5 == 0)
print "divisibility test: ", div_by_5

answer = num_array[div_by_5]
print "answer: ", answer

numbers:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
divisibility test:  [False False False False  True False False False False  True False False
 False False  True False False False False]
answer:  [ 5 10 15]


### Using NumPy functions

In [212]:
# Print all numbers within [1, 40] divisible by 5 and 7
num_array = np.arange(1, 41)
print "sequence: ", num_array

div_by_5 = num_array % 5 == 0
print "divisible by 5: ", div_by_5

div_by_7 = num_array % 7 == 0
print "divisible by 7: ", div_by_7

div_by_5_and_7 = np.logical_and(div_by_5, div_by_7)
print "divisible by 5 and 7: ", div_by_5_and_7

print "answer: ", num_array[div_by_5_and_7]

sequence:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
divisible by 5:  [False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True]
divisible by 7:  [False False False False False False  True False False False False False
 False  True False False False False False False  True False False False
 False False False  True False False False False False False  True False
 False False False False]
divisible by 5 and 7:  [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False]
answer:  [35]


## Broadcasting

In [213]:
my_array = np.arange(35).reshape(7,5)
print my_array

# print dimensions of the array
print "shape: ", my_array.shape

# print size (number of elements) in the array
print "size: ", my_array.size

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
shape:  (7, 5)
size:  35


In [214]:
# matrix multiplication
matrix_1 = np.arange(24).reshape(8, 3)
print matrix_1

matrix_2 = np.arange(15).reshape(3, 5)
print matrix_2

result = np.dot(matrix_1, matrix_2)
print result

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 25  28  31  34  37]
 [ 70  82  94 106 118]
 [115 136 157 178 199]
 [160 190 220 250 280]
 [205 244 283 322 361]
 [250 298 346 394 442]
 [295 352 409 466 523]
 [340 406 472 538 604]]


In [215]:
# adding matrices along different axis (dimensions)

# generating 3D matrix
my_array = np.arange(90).reshape(2,5,9)
print my_array

print my_array.sum(0)         # produces a matrix excluding 0th dimension and result is matrix of dim (5, 9)
print my_array.sum(1)         # produces a matrix excluding 1st dimension and result is matrix of dim (2, 9)   
print my_array.sum(2)         # produces a matrix excluding 2nd dimension and result is matrix of dim (2, 5)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]
  [27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44]]

 [[45 46 47 48 49 50 51 52 53]
  [54 55 56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69 70 71]
  [72 73 74 75 76 77 78 79 80]
  [81 82 83 84 85 86 87 88 89]]]
[[ 45  47  49  51  53  55  57  59  61]
 [ 63  65  67  69  71  73  75  77  79]
 [ 81  83  85  87  89  91  93  95  97]
 [ 99 101 103 105 107 109 111 113 115]
 [117 119 121 123 125 127 129 131 133]]
[[ 90  95 100 105 110 115 120 125 130]
 [315 320 325 330 335 340 345 350 355]]
[[ 36 117 198 279 360]
 [441 522 603 684 765]]


## Views and Copies

**Views** provide two or more references to the same memory location.

**Copy** takes data from one location in memory and replicates/duplicates it in another location in memory.

In [216]:
ref1 = np.array(np.arange(10))
ref2 = ref1                        # we are creating a different view here viz. 'ref2'

# Checking reference equality
print ref1 is ref2

# Both 'ref1' and 'ref2' point to same memory location but different views is all. Let's verify it
print "memory location of ref1: ", id(ref1)
print "memory location of ref2: ", id(ref2)

# Also, they both have the same value
print "ref1 value: ", ref1
print "ref2 value: ", ref2

# changing the value of one variable changes the value of other variable as well as they point to same location
print "ref1 original value: ", ref1
ref2[2] = 100
print "ref1 changed value: ", ref2

True
memory location of ref1:  139945812775040
memory location of ref2:  139945812775040
ref1 value:  [0 1 2 3 4 5 6 7 8 9]
ref2 value:  [0 1 2 3 4 5 6 7 8 9]
ref1 original value:  [0 1 2 3 4 5 6 7 8 9]
ref1 changed value:  [  0   1 100   3   4   5   6   7   8   9]


### Example of Views (Shallow Copy)

In [217]:
# create an array
arr1 = np.array(np.arange(10))
print "arr1: ", arr1

# create a view of the origial array
arr2 = arr1.view()
arr2 = arr2.reshape(5,2)
print "arr2: ", arr2

# change a value in arr1
arr1[0] = 111
print "changed arr1: ", arr1

# noice that the change is reflected in arr2
print "changes reflected in arr2: ", arr2

arr1:  [0 1 2 3 4 5 6 7 8 9]
arr2:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
changed arr1:  [111   1   2   3   4   5   6   7   8   9]
changes reflected in arr2:  [[111   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]


### Example of Copy (Deep Copy)

In [218]:
# create an array
arr1 = np.array(np.arange(10))
print "arr1: ", arr1

# create a copy 
arr2 = np.copy(arr1)
print "arr2: ", arr2

# change a value in arr1
arr1[0] = 111
print "changed arr1: ", arr1

# change not reflected in arr2
print "arr2 unchanged: ", arr2

arr1:  [0 1 2 3 4 5 6 7 8 9]
arr2:  [0 1 2 3 4 5 6 7 8 9]
changed arr1:  [111   1   2   3   4   5   6   7   8   9]
arr2 unchanged:  [0 1 2 3 4 5 6 7 8 9]


## Array Attributes

In [219]:
my_array = np.arange(24).reshape(3, 4, 2)
print "Order of the matrix: ", my_array.shape
print "Num. of elements: ", my_array.size
print "No. of dimensions: ", my_array.ndim

Order of the matrix:  (3, 4, 2)
Num. of elements:  24
No. of dimensions:  3


## Add and remove elements from NumPy array

In [220]:
a = np.arange(36).reshape(3, 2, 6)
print a

# create matrix 'b'
b = np.append(a, [111, 222, 333, 444, 555, 666])
print b.shape
print b.size

b = b.reshape(2, 3, 7)
print b.shape
print b.size

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
(42,)
42
(2, 3, 7)
42


In [221]:
# appending along specific axises
a = np.arange(42).reshape(3, 7, 2)
print "matrix a: ", a.shape

b = np.zeros(42, dtype = 'int32').reshape(3, 7, 2)
print "matrix b: ", b.shape

c_axis_0 = np.append(a, b, axis = 0)
print "matrix c_axis_0: ", c_axis_0.shape

c_axis_1 = np.append(a, b, axis = 1)
print "matrix c_axis_1: ", c_axis_1.shape

c_axis_2 = np.append(a, b, axis = 2)
print "matrix c_axis_2: ", c_axis_2.shape

matrix a:  (3, 7, 2)
matrix b:  (3, 7, 2)
matrix c_axis_0:  (6, 7, 2)
matrix c_axis_1:  (3, 14, 2)
matrix c_axis_2:  (3, 7, 4)


### *numpy.hstack()*

In [222]:
# Horizontal stacking -- clean function that doesn't need 'axis' attribute
a = np.arange(42).reshape(3, 7, 2)
b = np.zeros(42, dtype = 'int32').reshape(3, 7, 2)
c = np.hstack((a,b))
print "a: ", a.shape
print "b: ", b.shape
print "c: ", c.shape

# It creates copies and not views
c[0, 0, 0] = 111
print a[0, 0, 0]
print b[0, 0, 0]
print c[0, 0, 0]

a:  (3, 7, 2)
b:  (3, 7, 2)
c:  (3, 14, 2)
0
0
111



### *numpy.delete()*, *numpy.copyto()*, *numpy.empty()*

In [223]:
# create array 'a'
a = np.arange(42).reshape(2, 7, 3)

# create an empty array 'b' and copy all values of 'a' to 'b'
b = np.empty(a.shape)
np.copyto(b, a)
print "b: ", b.shape

# delete along specific axises
b_axis_0 = np.delete(b, 1, axis = 0)
print "b: ", b_axis_0.shape

b_axis_1 = np.delete(b, 1, axis = 1)
print "b: ", b_axis_1.shape

b_axis_2 = np.delete(b, 1, axis = 2)
print "b: ", b_axis_2.shape

b:  (2, 7, 3)
b:  (1, 7, 3)
b:  (2, 6, 3)
b:  (2, 7, 2)


## Concatenate and split arrays

### *numpy.concatenate()*

In [224]:
a = np.arange(30).reshape(3, 2, 5)
b = np.ones(30).reshape(3, 2, 5)
print "a: ", a.shape
print "b: ", b.shape

# concatenate along axis-0
c = np.concatenate((a,b), axis = 0)
print "c: ", c.shape

# concatenate along axis-1
c = np.concatenate((a,b), axis = 1)
print "c: ", c.shape

# concatenate along axis-2
c = np.concatenate((a,b), axis = 2)
print "c: ", c.shape

a:  (3, 2, 5)
b:  (3, 2, 5)
c:  (6, 2, 5)
c:  (3, 4, 5)
c:  (3, 2, 10)


### *numpy.split()*

In [225]:
a = np.arange(30).reshape(3, 5, 2)

# split 'a' into 3 arrays along axis = 0
# note that each of the 3 arrays has the shape (1, 5, 2)
split_axis_0 = np.split(a, 3, axis = 0)
print type(split_axis_0)
print split_axis_0[0].shape

# split 'a' into 5 arrays along axis = 1
# note that each of the 5 arrays has the shape (3, 1, 2)
split_axis_1 = np.split(a, 5, axis = 1)
print type(split_axis_1)
print split_axis_1[0].shape

# split 'a' into 2 arrays along axis = 2
# note that each of the 2 arrays has the shape (3, 5, 1)
split_axis_2 = np.split(a, 2, axis = 2)
print type(split_axis_2)
print split_axis_2[0].shape

<type 'list'>
(1, 5, 2)
<type 'list'>
(3, 1, 2)
<type 'list'>
(3, 5, 1)


## Array shape manipulation

### *numpy.reshape()*

In [226]:
# create a 3x4 matrix
my_array = np.arange(12).reshape(3,4)
print my_array.shape
print my_array

# changing it to 2x6 matrix
my_array_reshaped = np.reshape(my_array, (2, 6))
print my_array_reshaped.shape
print my_array_reshaped

# check if it creates a view or copy
my_array_reshaped[0, 0] = 1234
print my_array

# It can be seen that view has been created and not copy

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1234    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


### *numpy.ravel() -- flattens and returns an array*

In [227]:
# create an array
my_array = np.arange(15).reshape(5,3)
print "shape of original array: ", my_array.shape

# ravel the original array i.e. create a flat array
my_ravel_array = np.ravel(my_array)
print "shape of reveled array: ", my_ravel_array.shape

shape of original array:  (5, 3)
shape of reveled array:  (15,)


### *numpy.flat() -- flattens and returns an iterator* 

In [228]:
# create an array
my_array = np.arange(20,35).reshape(5,3)
print "shape of original array: ", my_array.shape

# flatten the original array 
flattened = my_array.flat
for i in flattened:
    print i

shape of original array:  (5, 3)
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34


## Rearranging array elements

### *numpy.rot90()*

In [229]:
# create an array
my_array = np.arange(21).reshape((3,7))
print "original array: "
print my_array

# rotate 90-degrees anti-clockwise
my_array_90 = np.rot90(my_array)
print "rotated 90 degrees anti-clockwise: "
print my_array_90

# rotate 90-degrees clockwise
my_array_90 = np.rot90(my_array, k = -1)
print "rotated 90 degrees clockwise: "
print my_array_90

original array: 
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
rotated 90 degrees anti-clockwise: 
[[ 6 13 20]
 [ 5 12 19]
 [ 4 11 18]
 [ 3 10 17]
 [ 2  9 16]
 [ 1  8 15]
 [ 0  7 14]]
rotated 90 degrees clockwise: 
[[14  7  0]
 [15  8  1]
 [16  9  2]
 [17 10  3]
 [18 11  4]
 [19 12  5]
 [20 13  6]]


## Writing my own python functions

I intend to create my own function named ** *squares* ** that takes numpy 1D array as input and returns squares of numbers.

In [230]:
def squares(arr):
    return arr ** 2

In [231]:
# unit testing the function I created -- no output means that the use-case is valid
np.testing.assert_equal(squares(5), 25)

In [232]:
# an error shows that use-case is invalid
np.testing.assert_equal(squares(5), 26)

AssertionError: 
Items are not equal:
 ACTUAL: 25
 DESIRED: 26

In [ ]:
# creating universal function for my created function
karthik_squares = np.frompyfunc(squares, 1, 1)

# using the universal function
karthik_squares([1, 2, 3])

## Linear Algebra

In [ ]:
# create a matrix 
my_matrix = np.matrix([[3, 5, -1],[2, 0, -4],[5, -1, 2]])
my_matrix

In [ ]:
# Inverse of a matrix
my_matrix.I

In [ ]:
# Transpose of a matrix
my_matrix.T

In [ ]:
# finding solution for system of linear equations i.e. find X such that below equation holds
# (my_matrix * X) = RHS 
# (3x3) * (3x1) = (3x1)

# solution: X = Inverse(my_matrix) * RHS

RHS = np.matrix([[6], [0], [-2]])
X = my_matrix.I * RHS
X

In [ ]:
# Testing the correctness of the solution
# (my_matrix * X) should be equal to RHS
my_matrix * X